# # This file defines the dvc stages and its depencies
# vars:
#   - birdset_python: /opt/birdset-env/bin/python

stages:
  load_raw_data:
    cmd:
      python source/load_raw_data.py
    deps:
      - source/load_raw_data.py
    params:
      - general.random_seed
      - dataset.name
      - dataset.subset
      - dataset.split
      - dataset.sampling_rate
    outs:
      - ${paths.raw_dataset}
  mix_audio:
    cmd: 
      #${birdset_python} source/dataset.py
      python source/mix_audio.py #venv/bin/python
    deps:
      - source/mix_audio.py 
      - ${paths.raw_dataset}
    params:
      - general.random_seed
      - dataset.sampling_rate
      - dataset.max_polyphony_degree
      - dataset.segment_duration
      - dataset.name
      - dataset.split
    outs:
      - ${paths.polyphonic_dataset}
  preprocess:
    cmd: python source/preprocess.py
    deps:
      - source/preprocess.py
      - ${paths.polyphonic_dataset}
    params:
      - embeddings.models
      - embeddings.feature
    outs:
    - ${paths.preprocessed_dataset}
