# # This file defines the dvc stages and its depencies
# vars:
#   - birdset_python: /opt/birdset-env/bin/python

stages:
  load_raw_data:
    cmd:
      python source/load_raw_dataset.py
    deps:
      - source/load_raw_dataset.py
    params:
      - general.random_seed
      - dataset.name
      - dataset.subset
      - dataset.split
      - dataset.sampling_rate
      - paths.raw_dataset
    outs:
      - ${paths.raw_dataset}
  mix_data:
    cmd: 
      #${birdset_python} source/dataset.py
      python source/mix_dataset.py #venv/bin/python
    deps:
      - source/mix_dataset.py 
      - ${paths.raw_dataset}
    params:
      - general.random_seed
      - dataset.sampling_rate
      - dataset.max_polyphony_degree
      - dataset.segment_duration
      - dataset.name
      - dataset.split
      - paths.raw_dataset
      - paths.mixed_dataset
    outs:
      - ${paths.mixed_dataset}
  preprocess:
    cmd: python source/preprocess.py
    deps:
      - source/preprocess.py
      - ${paths.mixed_dataset}
    params:
      - embeddings.models
      - embeddings.feature
    outs:
    - ${paths.preprocessed_dataset}
  

  # preprocess: 
  #   cmd: python source/preprocess.py
  #   deps:
  #   - source/preprocess.py
  #   - data/raw/
  #   params:
  #   - preprocess.input_path
  #   - preprocess.output_file_path
  #   - preprocess.test_split
  #   outs:
  #   - data/processed/
  # train:
  #   cmd: python source/train.py
  #   deps:
  #   - source/train.py
  #   - source/model.py
  #   - data/processed/
  #   params:
  #   - model._target_
  #   - model.input_size
  #   - train.batch_size
  #   - train.learning_rate
  #   - train.epochs
  #   - train.device_request # needed?
  #   - train.input_file_path
  #   - train.output_file_path
  #   outs:
  #   - models/checkpoints/
  # export:
  #   cmd: python source/export.py
  #   deps:
  #   - source/export.py
  #   - models/checkpoints/
  #   params:
  #   - model._target_
  #   - model.input_size
  #   - export.output_file_path
  #   outs:
  #   - models/exports/
  # save_logs:
  #   cmd: python source/utils/logs.py
  #   deps:
  #   - source/utils/logs.py
  #   outs:
  #   - exp_logs/
