general:
  random_seed: 42
dataset:
  raw_dataset_dir: data/raw_datasets/
  mixed_dataset_dir: data/mixed_datasets/
  dataset_key: HSN_xc
  dataset_split: train
  sampling_rate: 32000
  segment_duration: 3
  max_polyphony_degree: 5
preprocess:
  input_path: data/raw/
  output_file_path: data/processed/data.pt
  test_split: 0.2
model:
  _target_: model.Conv1DAutoencoder
  input_size: 8000
train:
  batch_size: 4096
  learning_rate: 0.03
  epochs: 5
  device_request: cuda
  input_file_path: data/processed/data.pt
  output_file_path: models/checkpoints/model.pth
export:
  output_file_path: models/exports/model.pth
