general:
  random_seed: 42
dataset:
  name: DBD-research-group/BirdSet
  subset: HSN_xc
  split: train
  sampling_rate: 32000
  segment_duration: 5
  max_polyphony_degree: 7
embeddings:
  models:
  - perch_8
  - yamnet
  feature: audio
preprocess:
  input_path: data/raw/
  output_file_path: data/processed/data.pt
  test_split: 0.2
model:
  _target_: model.Conv1DAutoencoder
  input_size: 8000
train:
  features: yamnet_embeddings
  labels: polyphony_degree
  pooling_strategy: mean
  test_split: 0.1
  val_split: 0.1
  batch_size: 32
  learning_rate: 0.03
  epochs: 5
export:
  output_file_path: models/exports/model.pth
paths:
  raw_dataset: data/raw_datasets/HSN_xc
  polyphonic_dataset: data/polyphonic_datasets/HSN_xc_polyphonic
  preprocessed_dataset: data/preprocessed_datasets/HSN_xc_preprocessed
